image: atlassian/default-image:2

pipelines:
  default:
    - step:
        name: "Build and Test"
        services:
          - docker
        script:
          - IMAGE="mspipes/azure-vote-front"
          - VERSION="$BITBUCKET_BUILD_NUMBER"
          - echo ${DOCKERHUB_PASSWORD} | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
          - docker build -t ${IMAGE} .
          - docker tag ${IMAGE} ${IMAGE}:${VERSION}
          - docker push ${IMAGE}
    - step:
        name: "Deploy to PROD"
        deployment: production
        script:
          - sed -i "s/azure-vote-front:{{version}}/azure-vote-front:$BITBUCKET_BUILD_NUMBER/g" azure-vote-prod.yml
          - cat azure-vote-prod.yml
          - pipe: microsoft/azure-aks-deploy:1.0.0
            variables:
              AZURE_APP_ID: $AZURE_APP_ID
              AZURE_PASSWORD: $AZURE_PASSWORD
              AZURE_TENANT_ID: $AZURE_TENANT_ID
              AZURE_AKS_NAME: "my-cluster-create"
              AZURE_RESOURCE_GROUP: "my-resource-delete"
              KUBECTL_COMMAND: 'apply'
              KUBERNETES_SPEC_FILE: 'azure-vote-prod.yml'

